version: '3.7'

services:
  django:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - logstash 
    volumes:
      - .:/usr/src/app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0 
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    ports:
      - "5000:5000" 
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch 

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0 
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
    esdata:
      driver: local